### ISSUE TITLE
Monthly bandwidth allowance calculation broke in latest version v2.0.4

### ISSUE THREAD

**Issue by ILAsoft** [de-vnull/vnstat-on-merlin#25]
Has been working great for months/years, but latest version throws error and corrupts output:
awk: cmd. line:1: Division by zero
You have used % (38.98
15.21GB) of your 1200.00GB cycle allowance; the next cycle starts on day 14 of the month.

All other areas seem fine and displaying proper information. Reinstalling and force-updating do not seem to help. Switching storing location did not seem to help either. Note, I opted not to drop the history/config on uninstall, so it is possible that something is off in the prior historical files (eg from December).

**Comment by de-vnull** [comment]
Thanks for reporting. This was an error we saw before but no one else has reported.

Can you please detail what you upgraded at the time this occurred (e.g., Entware, other add-ons) and what your current setup looks like (router model, firmware version, add-ons, type of connection, etc).

I will get with @jackyaz once we have some information on your environment and the situation in hand.

**Comment by ILAsoft** [comment]
ASUSWRT-Merlin RT-AX86U 386.4_0 
 amtm 3.2.3 FW             by thelonelycoder
 RT-AX86U (aarch64) FW-386.4 @ 192.168.212.1
    The Asuswrt-Merlin Terminal Menu

 1  open     Diversion                 v4.2.1
 2  open     Skynet        v7.2.8  -> min upd
 3  open     FlexQoS                   v1.3.0

 4  open     YazFi                     v4.4.1
 5  open     scribe                    v2.4.3

 8  open     nsrum                    v30.4.0

 j1 open     connmon                   v3.0.2
 j3 open     scMerlin                  v2.4.0

 j4 open     spdMerlin                 v4.4.4
 j5 open     uiDivStats                v3.0.2
 j6 open     uiScribe                  v1.4.5

 j7 open     YazDHCP                   v1.0.3
 vn open     vnStat                    v2.0.4

 di open     dnscrypt installer        v2.3.1
 wg open     WireGuard Mgr              v4.13

 ep manage   Entware packages

 em open     email settings
 dc manage   Disk check script   dcl show log
 fd run      Format disk         fdl show log
 sw manage   Swap file /mnt/500GbSabr 2.0G

 i  show     all available scripts or tools
 u  check    for script updates

    amtm options
 e  exit      t  theme   r  reset   a  about
_____________________________________________

A bit hard for me to confidently say what all I upgraded at the time, but I believe both vnstat and the firmware itself were upgraded (from the version right before this one). In fact, initially vnstat upgrade failed and I had to follow guidance from https://github.com/de-vnull/vnstat-on-merlin/issues/23 to cleanup and reinstall.
Please let me know if any additional logging or specific information would help trace this odd issue (which continues to show up on the every day emails). Thank you very much!!!

**Comment by de-vnull** [comment]
Sorry for the delay in responding, I've had a lot of other commitments since the new year started (job, community, family).

First let's save the data. See this post: https://www.snbforums.com/goto/post?id=707414

Once you've copied "vnstat.db" (someplace permanent, like your usb drive; do not leave it in /root or any dynamic flash area) then let's completely uninstall dn-vnstat. When prompted *do not* save the configuration or data file (you just saved that). 

I'd recommend rebooting after this, but if that's not possible, go back in and reinstall (from amtm, type "vn" and you should be prompted to install. Make sure it identifies the correct interface.

Once installed, give it a couple of minutes to collect some data, then check to see if the error is present. If it's not, then it was something with the configuration. We can then restore the database you backed up. (To restore the db, at the CLI enter "/opt/etc/init.d/S33vnstat stop", then copy the db back to the original location (make sure that in the configuration you've chosen usb or jffs for the location). Once the file is copied back, then issue "/opt/etc/init.d/S33vnstat start". This should read the db file and show the data that was saved.)

If the error is still present, then there's something else afoot. This error has been previously reported in other JackYaz apps and even in dn-vnstat once (Jack has been generous to allow dn-vnstat to reuse some of the underpinning code). In the past there were hotfixes issued, but this is not a widespread issue (e.g., it's just you right now).

I'm hoping the above fixes it, otherwise I'll reach out to Jack to ask for some additional help.
