### ISSUE TITLE
Monthly Usage showing incorrect information

### ISSUE THREAD

**Issue by AdziePahlevi** [de-vnull/vnstat-on-merlin#28]
Dear Expert, 

thanks a lot in advance for providing great feature for AsusWRT Merlin and also tremendous support that you have done so far.

I would like to report some issues that I have noticed recently regarding monthly usage, below is snapshot from my router.

as you can see there are variance usage between GB and TB, however total usage is calculated in GB units that causing incorrect information. 

![image](https://user-images.githubusercontent.com/19539988/212817732-7e5158a1-2545-4a30-99a9-d826f955febd.png)

below is my vnstat detail and release information 

![image](https://user-images.githubusercontent.com/19539988/212818167-38862235-079c-40be-b5e2-969c2b6c02c8.png)

this is minor issue and did not affecting any other functions, if possible, please kindly include the fix in the next vnstat release. 

thanks a lot for all the good works and have a good day,

**Comment by de-vnull** [comment]
I must be missing exactly what the issue is. The math I'm seeing works - e.g., 2.10TB + 0.42736TB = 2.52736TB, shown as 2.53TB which correctly rounded. The addition on each of these seem correct to me.

Can you please elaborate? It's likely I'm missing something that's staring me right in the face, but...

(Aside: what I do see is that you potentially have hardware acceleration enabled (the two months of 2.10TB/430GB) so any numbers here are likely to be inaccurate (see notes within the thread on snbforums w/r/t to hardware acceleration inaccuracies. But that shouldn't break the math.))

**Comment by jackyaz** [comment]
It's possible the user is misreading the "Estimated" row as a total?

**Comment by de-vnull** [comment]
> It's possible the user is misreading the "Estimated" row as a total?

Yeah, I suppose that is possible too.

**Comment by de-vnull** [comment]
@AdziePahlevi - as Jack notes, the line at the bottom is not a summary but rather an estimate of the current month usage based on usage to date. It is a built-in function of vnstat (the Linux app) and there's no way for it to be customized.

**Comment by AdziePahlevi** [comment]
I see, so its not counting the total usage, instead it is showing for estimates value... 

okay then, thanks a lot @jackyaz @de-vnull for enlightenment....
