### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by csm10495** [de-vnull/vnstat-on-merlin#30]
If I enable and setup email notifications, when do they get sent? Can I make them send at certain percentages used? (Like 25%, 50%, etc.)

I checked the docs but didn't seem to see this part explained. Thanks!

**Comment by de-vnull** [comment]
If you've installed using the amtm menu function, then a cron job is set to email the daily reports at 11.59PM local.

The approaching/exceeding limit message would go out once that threshold is crossed (so, pretty much anytime).

In theory you could fork and modify the script to either change the values (or potentially add other triggers), starting around line 1375. TBH, I look at the daily reports, which estimate what will be used at the end of the month based on the use to date, and there is a 75%, 90% and 100% notification already.

If you fork it, please post on snbforums so that others can take advantage of any modifications, as others may be interested in the same.

PS thanks for using the script. I appreciate hearing from folks who are using it.

**Comment by csm10495** [comment]
Would you consider merging a PR that adds the specific functionality I'm asking about?

Mainly just emails for passing custom thresholds, as a separate setting from daily emails.

**Comment by de-vnull** [comment]
Yes, I would. I'm just starting a new job, so I won't have time to test, I presume you'll be willing to do so?

**Comment by csm10495** [comment]
Maybe eventually. Close this out for now, if I ever get to it, I'll post a PR and test on my router. Thanks again.
